#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : setserial
Version  : 2.17
Release  : 7
URL      : https://sourceforge.net/projects/setserial/files/setserial/2.17/setserial-2.17.tar.gz
Source0  : https://sourceforge.net/projects/setserial/files/setserial/2.17/setserial-2.17.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: setserial-bin = %{version}-%{release}
Requires: setserial-man = %{version}-%{release}
BuildRequires : groff
Patch1: build.patch

%description
setserial Version 2.17 (27-Jan-2000)
Setserial is a program which allows you to look at and change various
attributes of a serial device, including its port, its IRQ, and other
serial port options.

%package bin
Summary: bin components for the setserial package.
Group: Binaries
Requires: setserial-man = %{version}-%{release}

%description bin
bin components for the setserial package.


%package man
Summary: man components for the setserial package.
Group: Default

%description man
man components for the setserial package.


%prep
%setup -q -n setserial-2.17
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1545262332
%configure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1545262332
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/setserial

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/setserial.8
